package mysql

import (
	"database/sql"
	"fmt"
	"os"
	"strings"
	"testing"
	"time"

	"github.com/go-sql-driver/mysql"
)

const (
	defaultTestEndpoint = "localhost:3306"
	testUsername        = "root"
	testPassword        = "datastorectl"
)

// testEndpoint holds the resolved MySQL endpoint (host:port). Empty
// means no cluster is available — integration tests are skipped.
var testEndpoint string

// testServerVersion holds the live cluster's major.minor (e.g. "8.4").
// Integration tests use this as their declared `version` so Configure
// matches whatever server the harness is pointed at.
var testServerVersion string

func TestMain(m *testing.M) {
	endpoint := os.Getenv("DATASTORECTL_MYSQL_TEST_ENDPOINT")
	if endpoint == "" {
		endpoint = defaultTestEndpoint
	}

	if ver, ok := clusterVersion(endpoint); ok {
		testEndpoint = endpoint
		testServerVersion = ver
	} else {
		fmt.Fprintf(os.Stderr,
			"mysql: cluster not reachable at %s — skipping integration tests "+
				"(set DATASTORECTL_MYSQL_TEST_ENDPOINT or run docker compose -f docker-compose.mysql.yml up)\n",
			endpoint)
	}

	os.Exit(m.Run())
}

// clusterVersion opens a short-lived connection via the MySQL driver,
// runs SELECT VERSION(), and returns the server's major.minor. TLS is
// skip-verify to tolerate self-signed certs auto-generated by mysql
// images. Returns "", false when the cluster is unreachable or its
// version is outside the declared-supported set.
func clusterVersion(endpoint string) (string, bool) {
	cfg := mysql.NewConfig()
	cfg.User = testUsername
	cfg.Passwd = testPassword
	cfg.Net = "tcp"
	cfg.Addr = endpoint
	cfg.TLSConfig = "skip-verify"
	cfg.AllowNativePasswords = true
	cfg.Timeout = 3 * time.Second
	cfg.ReadTimeout = 3 * time.Second
	cfg.WriteTimeout = 3 * time.Second

	db, err := sql.Open("mysql", cfg.FormatDSN())
	if err != nil {
		return "", false
	}
	defer db.Close()

	var raw string
	if err := db.QueryRow("SELECT VERSION()").Scan(&raw); err != nil {
		return "", false
	}

	// Extract major.minor from e.g. "8.4.5", "8.0.36-28", "8.0.35-aurora.3".
	clean := raw
	for i, r := range raw {
		if r == '-' || r == '+' {
			clean = raw[:i]
			break
		}
	}
	parts := strings.Split(clean, ".")
	if len(parts) < 2 {
		fmt.Fprintf(os.Stderr, "mysql: unexpected server version %q, skipping integration tests\n", raw)
		return "", false
	}
	mm := parts[0] + "." + parts[1]
	if mm != "8.0" && mm != "8.4" {
		fmt.Fprintf(os.Stderr,
			"mysql: server at %s reports %s, which is outside the declared-supported set (8.0, 8.4); skipping integration tests\n",
			endpoint, raw)
		return "", false
	}
	return mm, true
}

// skipIfNoCluster skips t when no MySQL cluster is available.
func skipIfNoCluster(t *testing.T) {
	t.Helper()
	if testEndpoint == "" {
		t.Skip("no MySQL cluster available; set DATASTORECTL_MYSQL_TEST_ENDPOINT or run docker compose -f docker-compose.mysql.yml up")
	}
}
