package mysql

import (
	"database/sql"
	"fmt"
	"os"
	"testing"
	"time"

	"github.com/go-sql-driver/mysql"
)

const (
	defaultTestEndpoint = "localhost:3306"
	testUsername        = "root"
	testPassword        = "datastorectl"
)

// testEndpoint holds the resolved MySQL endpoint (host:port). Empty
// means no cluster is available — integration tests are skipped.
var testEndpoint string

func TestMain(m *testing.M) {
	endpoint := os.Getenv("DATASTORECTL_MYSQL_TEST_ENDPOINT")
	if endpoint == "" {
		endpoint = defaultTestEndpoint
	}

	if clusterReachable(endpoint) {
		testEndpoint = endpoint
	} else {
		fmt.Fprintf(os.Stderr,
			"mysql: cluster not reachable at %s — skipping integration tests "+
				"(set DATASTORECTL_MYSQL_TEST_ENDPOINT or run docker compose -f docker-compose.mysql.yml up)\n",
			endpoint)
	}

	os.Exit(m.Run())
}

// clusterReachable opens a short-lived connection via the MySQL driver
// and runs SELECT 1. TLS is skip-verify to tolerate self-signed certs
// auto-generated by mysql:8.4. Returns true if the ping succeeds.
func clusterReachable(endpoint string) bool {
	cfg := mysql.NewConfig()
	cfg.User = testUsername
	cfg.Passwd = testPassword
	cfg.Net = "tcp"
	cfg.Addr = endpoint
	cfg.TLSConfig = "skip-verify"
	cfg.AllowNativePasswords = true
	cfg.Timeout = 3 * time.Second
	cfg.ReadTimeout = 3 * time.Second
	cfg.WriteTimeout = 3 * time.Second

	db, err := sql.Open("mysql", cfg.FormatDSN())
	if err != nil {
		return false
	}
	defer db.Close()

	if err := db.Ping(); err != nil {
		return false
	}
	return true
}

// skipIfNoCluster skips t when no MySQL cluster is available.
func skipIfNoCluster(t *testing.T) {
	t.Helper()
	if testEndpoint == "" {
		t.Skip("no MySQL cluster available; set DATASTORECTL_MYSQL_TEST_ENDPOINT or run docker compose -f docker-compose.mysql.yml up")
	}
}
